### ISSUE TITLE
Uncaught Error: Not in a file context

### ISSUE THREAD

**Issue by gg7star** [ghepesdoru/atom-react-instyle#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-react-instyle](https://github.com/ghepesdoru/atom-react-instyle) package 0.2.8

### Stack Trace

Uncaught Error: Not in a file context

```
At /Users/pascal/.atom/packages/atom-react-instyle/lib/atom-react-instyle.js:159

Error: Not in a file context
    at AtomReactInstyle.convertAsFile (/packages/atom-react-instyle/lib/atom-react-instyle.js:159:13)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:21 application:new-file (input.hidden-input)
     -0:19.7.0 core:paste (input.hidden-input)
  3x -0:15.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
aligner-python 1.0.1 
atom-clock 0.1.7 
atom-django 0.3.2 
atom-dlang 1.1.2 
atom-electron-snippets 2.0.3 
atom-python-package 0.7.0 
atom-python-run 0.7.3 
atom-python-test 0.5.4 
atom-python-virtualenv 0.9.0 
atom-react-es2015-snippets 1.2.1 
atom-react-instyle 0.2.8 
atom-react-native-autocomplete 0.0.27 
atom-react-snippets 0.2.2 
autocomplete-python 1.8.63 
bdd-react-snippets 0.6.0 
browser-plus 0.0.87 
build 0.67.0 
build-python 0.9.1 
busy 0.7.0 
busy-signal 1.4.1 
django-atom 0.2.4 
django-templates 0.5.0 
django-test-runner 0.5.0 
django-wrap-i18n 0.6.0 
egghead-react-snippets 1.2.2 
hyperclick 0.0.40 
intentions 1.1.2 
ipython-exec 1.2.0 
lang-bolt 2.1.0 
language-django 0.1.1 
language-javascript-jsx 0.3.7 
language-mongodb 0.3.1 
language-swig 0.1.4 
language-yang 0.2.0 
linter 2.1.4 
linter-pycodestyle 2.0.2 
linter-python 3.1.1 
linter-ui-default 1.2.3 
linter-write-good 0.9.0 
MagicPython 1.0.9 
microbit-python 0.1.6 
minimap 4.28.1 
minimap-linter 2.0.0 
modern-react-snippets 0.3.0 
multiline-select 1.8.2 
python-debugger 0.2.0 
python-for-glyphs 0.1.0 
python-indent 1.0.2 
python-iresolve 0.0.3 
python-isort 0.0.7 
python-jedi 0.3.8 
python-line-profiler 0.2.1 
python-mrigor 2.1.3 
python-nosetests 0.2.0 
python-run-terminalnx 1.0.3 
python-snippets 1.9.0 
python-tools 0.6.9 
python-yapf 0.13.0 
pythonic-atom 0.1.8 
react-es6-snippets 0.3.0 
react-es7-snippets 0.3.13 
react-function-to-class 0.2.1 
react-native-snippets 0.3.0 
react-native-snippets-horse 2.0.0 
react-redux-atom-snippets 0.7.2 
react-redux-component-snippets 0.0.3 
react-redux-es6-snippets 0.1.3 
react-redux-react-native-snippets 0.2.4 
react-redux-snippets 0.1.6 
react-snippets 0.7.2 
rhino-python 0.8.4 
run-python-simply 0.1.1 
script 3.14.1 
simply-django-atom 0.0.2 
source-preview-react 0.2.0 
standard-react-snippets 2.0.0 
```

**Comment by ghepesdoru** [comment]
Solved in 0.3.1
