### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by ghost** [ghepesdoru/atom-react-instyle#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-react-instyle](https://github.com/ghepesdoru/atom-react-instyle) package 0.2.8

### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /Users/surajkongara/.atom/packages/atom-react-instyle/lib/atom-react-instyle.js:214

TypeError: Cannot read property 'file' of undefined
    at AtomReactInstyle.getCurrentFile (/packages/atom-react-instyle/lib/atom-react-instyle.js:214:33)
    at AtomReactInstyle.convertAsFile (/packages/atom-react-instyle/lib/atom-react-instyle.js:156:23)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  2x -0:14.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
angular-2 0.2.6 
angular-2-typeScript-snippets 0.7.0 
angular-bootstrap 1.0.1 
angular2-snippets 0.4.0 
angular2-snippets-atom 0.7.0 
angularjs 0.4.0 
angularjs-helper 0.10.2 
angularjs-snippets 0.10.18 
angularjs-styleguide-snippets 0.9.1 
atom-angular-material-snippets 1.3.0 
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
atom-css-clean 2.21.0 
atom-css-unit-converter 1.1.1 
atom-javascript-console-snippets 0.10.0 
atom-node-debugger 2.1.2 
atom-nodejs-snippets 1.5.0 
atom-react-instyle 0.2.8 
atom-react-snippets 0.2.2 
autoclose-html 0.23.0 
autocomplete-angular-material 0.4.0 
autocomplete-html-entities 0.1.0 
autocomplete-javascript 0.0.2 
badass-react-snippets 1.1.0 
best-js-snippets 4.1.0 
bootstrap-3-snippetset 0.0.6 
bootstrap-sass-snippets 2.1.1 
bootstrap4-snippets 0.2.2 
css-comb 2.5.0 
css-from-html 0.1.5 
css-snippets 1.1.0 
css-specificity 0.2.2 
emmet-jsx-css-modules 1.0.0 
es6-javascript 1.0.0 
expressjs 2.1.1 
format-javascript-comment 0.2.4 
html-head-snippets 0.2.0 
html-nested-comments 3.3.1 
html-shorcuts-react 1.0.0 
html-tab 1.0.2 
html-to-css 0.2.2 
html-to-javascript 0.2.0 
javascript-object-snippets 0.3.0 
javascript-refactor 0.5.7 
javascript-snippets 1.2.1 
javascript-standard-snippets 0.2.1 
language-javascript-jsx 0.3.7 
language-javascript-jxa 0.2.8 
language-javascript-semantic 0.2.1 
laravel-forms-bootstrap-snippets 1.2.0 
modern-react-snippets 0.3.0 
node-debug 0.1.7 
node-debugger 1.10.1 
node-resolver 1.0.1 
nodejs-snippets 2.0.2 
open-html-in-browser 0.1.0 
react-es6-snippets 0.3.0 
react-es7-snippets 0.3.13 
react-native-snippets 0.3.0 
react-redux-atom-snippets 0.7.2 
react-redux-es6-snippets 0.1.3 
react-redux-react-native-snippets 0.2.4 
react-snippets 0.8.0 
standardjs-snippets 2.6.0 
titanium-language-javascript 0.48.0 
turbo-javascript 1.4.0 
v-bootstrap4 0.1.8 
xatom-debug-nodejs 0.9.3 
```

**Comment by ghepesdoru** [comment]
Fixed in 0.3.2
