### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by fukai007** [ghepesdoru/atom-react-instyle#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-react-instyle](https://github.com/ghepesdoru/atom-react-instyle) package 0.2.8

### Stack Trace

Uncaught TypeError: Cannot read property 'forEach' of undefined

```
At /Users/fukai/.atom/packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:352

TypeError: Cannot read property 'forEach' of undefined
    at /packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:352:29
    at Function.transformItem (/packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:464:11)
    at /packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:335:21
    at Array.forEach (native)
    at Function.transformItem (/packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:334:11)
    at /packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:345:25
    at Function.transformItem (/packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:464:11)
    at Function.transform (/packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:322:19)
    at Convertor.convert (/packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:818:28)
    at AtomReactInstyle.convert (/packages/atom-react-instyle/lib/atom-react-instyle.js:126:20)
    at AtomReactInstyle.convertAsFile (/packages/atom-react-instyle/lib/atom-react-instyle.js:167:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/fukai/Desktop/develop/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Users/fukai/Desktop/develop/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/fukai/Desktop/develop/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/fukai/Desktop/develop/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/fukai/Desktop/develop/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Users/fukai/Desktop/develop/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:01.5.0 application:reopen-project (atom-pane.pane.active)
  3x -0:55.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.4 
atom-bracket-highlight 0.3.2 
atom-emacs-calc 1.2.0 
atom-mac-terminal 1.0.4 
atom-material-ui 2.0.4 
atom-nodejs-snippets 1.5.0 
atom-react-instyle 0.2.8 
atom-react-native-autocomplete 0.0.27 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
autoprefixer 3.7.1 
block-comment 0.4.3 
busy-signal 1.4.3 
chrome-color-picker 0.8.0 
clang-format 1.29.0 
code-peek 1.4.20 
css-specificity 0.2.2 
cssfmt 1.4.0 
ctags-status 1.3.7 
docblockr 0.11.0 
editor-background 1.2.38 
emmet 2.4.3 
es6-javascript 1.0.0 
esformatter 2.3.0 
file-types 0.5.5 
format-sql 0.3.0 
formatter 2.12.4 
git-plus 7.9.3 
glowing-cursor 0.1.2 
goto-definition 1.3.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
html-to-css 0.2.2 
intentions 1.1.2 
javascript-snippets 1.2.1 
jQuery 1.2.5 
jquery-snippets 11.0.0 
jsformat 0.9.3 
jsx-comment 0.2.0 
language-javascript-jsx 0.3.7 
language-postcss 1.3.1 
language-scala 1.1.8 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.3 
minimap 4.29.0 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
node-debugger 1.10.1 
nodejs-snippets 2.0.2 
open-in-browser 0.5.2 
open-in-browsers 0.0.30 
open-recent 5.0.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.3 
px2rem-plus 0.3.1 
react 0.16.2 
react-native-snippets 0.3.0 
react-snippets 0.8.0 
require-anywhere 2.0.7 
rxjs-redux-snippets 1.3.2 
script 3.15.0 
seti-icons 1.5.4 
seti-ui 1.9.0 
standard-formatter 2.8.0 
sync-settings 0.8.2 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
tree-view-background 0.4.3 
```

**Comment by taime** [comment]
I had the same error in browser because I forgot add YMInitializer in root component of my app. (I thought putting counter script to index.html  would be enough, but it wasn't...

So Try add 

```
import { YMInitializer } from 'react-yandex-metrika';

<YMInitializer
      accounts={[12345678]}
      options={{
        clickmap: true,
        trackLinks: true,
        accurateTrackBounce: true,
        webvisor: true,
        trackHash: false
      }}
      version="2"
    />

```

p.s. replace 12345678 with your yandex metrika counter number
