### ISSUE TITLE
Uncaught Error: No implemented transformation for type: "supports".

### ISSUE THREAD

**Issue by Veeraphong** [ghepesdoru/atom-react-instyle#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: [atom-react-instyle](https://github.com/ghepesdoru/atom-react-instyle) package 0.2.8

### Stack Trace

Uncaught Error: No implemented transformation for type: "supports".

```
At C:\Users\pom\.atom\packages\atom-react-instyle\node_modules\react-instyle\lib\convertor.js:462

Error: No implemented transformation for type: "supports".
    at /packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:462:21
    at Function.transformItem (/packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:464:11)
    at /packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:335:21
    at Array.forEach (<anonymous>)
    at Function.transformItem (/packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:334:11)
    at /packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:345:25
    at Function.transformItem (/packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:464:11)
    at Function.transform (/packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:322:19)
    at Convertor.convert (/packages/atom-react-instyle/node_modules/react-instyle/lib/convertor.js:818:28)
    at AtomReactInstyle.convert (/packages/atom-react-instyle/lib/atom-react-instyle.js:126:20)
    at AtomReactInstyle.convertAsFile (/packages/atom-react-instyle/lib/atom-react-instyle.js:167:10)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:345848)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:1226096)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:1222230)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:281284)
```

### Commands

```
     -2:25.3.0 tree-view:paste (span.name.icon.icon-file-directory)
  6x -2:20.7.0 click (div.header.list-item)
     -1:46 tree-view:add-file (span.name.icon.icon-file-directory)
     -1:31.9.0 core:confirm (input.hidden-input)
     -1:12.5.0 core:paste (div.highlights)
 15x -0:17.7.0 intentions:highlight (input.hidden-input)
     -0:16.7.0 core:paste (input.hidden-input)
 22x -0:11.4.0 intentions:highlight (input.hidden-input)
     -0:10.2.0 core:save (input.hidden-input)
     -0:00.1.0 click (a.btn-issue.btn.btn-error)
```

### Non-Core Packages

```
artisan 0.3.2 
atom-debug-ui 1.0.4 
atom-eclipse-syntax 0.0.6 
atom-html-templates-extended 0.3.0 
atom-ide-ui 0.13.0 
atom-react-instyle 0.2.8 
atom-select-npm-install 1.0.2 
autocomplete-module-import 0.3.0 
autumn-highlighter-syntax 1.13.0 
blade-snippets 0.2.0 
blade-spacer 0.4.2 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
Hydrogen 2.6.0 
hyperclick 0.0.0 
ide-css 0.3.0 
ide-go 0.12.3 
ide-html 0.4.2 
ide-json 0.2.1 
ide-php 0.7.15 
ide-r 0.1.8 
intentions 1.1.5 
kernel-docstring 1.1.0 
language-blade 0.41.4 
laravel 0.7.1 
laravel-5-snippets 0.19.0 
laravel-eloquent-snippets 2.0.0 
laravel-forms-bootstrap-snippets 1.2.0 
laravel-helper 0.2.6 
laravel-snippets 2.1.0 
laravel-snippets-5 1.3.0 
laravelcollective-html-form-snippets 1.0.0 
linter 2.2.0 
linter-php 1.5.1 
linter-sass-lint 1.8.3 
linter-ui-default 1.7.1 
npm-install 4.0.4 
php-composer-completion 0.3.4 
php-cs-fixer 4.1.1 
php-debug 0.3.5 
php-extract-method 0.2.1 
php-fmt 0.1.2 
php-hyperclick 1.2.1 
php-integrator-autocomplete-plus 1.6.2 
php-integrator-base-legacy-php56 undefined 
php-integrator-navigation 1.2.1 
php-tools 0.1.0 
rainbow-tabs 2.5.1 
teletype 0.13.3 
```

**Comment by ghepesdoru** [comment]
Hello,

A potential fix for this issue might be in the .3.0 release of today.
The issue (based on what I could determine from the description) was in relationship with SASS not interpreting @supports correctly. This should be fixed with the SASS version bump, but let me know if you encounter any issues.

A sample SASS file could be helpful in case of further troubles also.
